### ISSUE TITLE
Testing ROS on Z7030

### ISSUE THREAD

**Issue by Pranjali-Shinde** [SundanceMultiprocessorTechnology/emc2-ros#1]
Hi Pedro,
I have downloaded the ROS image on the SD card and when I plug it on the board nothing emerges on the screen. Can I please know how should I proceed with it?  In order to test if everything is working right.

**Comment by pedrombmachado** [comment]
@timoteogb ,
   Can you please help @Pranjali-Shinde  with the next step.

**Comment by pedrombmachado** [comment]
@Pranjali-Shinde ,
   How do you have the board connected? Are using the UART terminal or the Ethernet? This version is not using the HDMI output because it is wired to the PL side and we do not have drivers ready.
  You can connect to the board via the UART terminal or over the Ethernet (once it is configured). 
The login is sundance and the password is also sundance.
You can configure the ethernet by editing the file:
```
$ sudo nano /etc/network/interfaces
```
in this file you can configure the ip, netmask and gateway. You will have to reboot after changing this file.
After rebooting you can access the board and route all the GUIs by running the following command from the client pc:
```
$ ssh -X <ip>
```

**Comment by pedrombmachado** [comment]
Sorted.
